type TtalkakId = string | number;
type TtalkakToken = string | undefined;
type TtalkakPayload = Record<string, unknown>;

interface TtalkakApi {
  login(payload: TtalkakPayload): Promise<unknown>;
  signup(payload: TtalkakPayload): Promise<unknown>;
  googleLogin(credential: string): Promise<unknown>;
  findId(payload: TtalkakPayload): Promise<unknown>;
  requestPasswordReset(payload: TtalkakPayload): Promise<unknown>;
  withdrawAccount(payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  checkUserId(userId: string): Promise<unknown>;
  checkNickname(nickname: string): Promise<unknown>;
  getCommunityPosts(options?: TtalkakPayload): Promise<unknown>;
  searchCommunityPosts(options?: TtalkakPayload): Promise<unknown>;
  getPopularTags(options?: TtalkakPayload): Promise<unknown>;
  searchTags(options?: TtalkakPayload): Promise<unknown>;
  proposeTag(payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  viewPrompt(promptId: TtalkakId): Promise<unknown>;
  improvePrompt(payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  savePrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  unsavePrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  likePrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  unlikePrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  getMakeThreads(token: TtalkakToken): Promise<unknown>;
  getMakeThread(threadId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  getMakeFolders(token: TtalkakToken): Promise<unknown>;
  createMakeThread(payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  deleteMakeThread(threadId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  createMakeFolder(payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  updateMakeFolder(folderId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  deleteMakeFolder(folderId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  moveMakeThread(threadId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  sharePrompt(payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  shareExistingPrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  updatePrompt(promptId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  deletePrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  unsharePrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  reportPrompt(promptId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  reportComment(commentId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getPromptComments(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  addComment(promptId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  addReply(commentId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  updateComment(commentId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  deleteComment(commentId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  likeComment(commentId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  unlikeComment(commentId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  getSavedPrompts(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getMyLibrary(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getMyPrompts(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getMyComments(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getMyReports(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getMyRevisionRequests(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  requestPromptRevision(promptId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminReports(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  updateAdminReportStatus(reportId: TtalkakId, status: string, token: TtalkakToken, memo?: string): Promise<unknown>;
  getAdminPrompts(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminTags(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  updateAdminTagStatus(tagId: TtalkakId, status: string, token: TtalkakToken): Promise<unknown>;
  searchAdminUsers(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminUserActivitySummary(memberId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  getAdminUserPrompts(memberId: TtalkakId, options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminUserComments(memberId: TtalkakId, options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminUserReplies(memberId: TtalkakId, options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminUserSubmittedReports(memberId: TtalkakId, options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminUserReceivedReports(memberId: TtalkakId, options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminUserActivity(memberId: TtalkakId, options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  blockAdminUser(memberId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  unblockAdminUser(memberId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  getAdminAuditLogs(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  getAdminRevisionRequests(options: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  requestAuthorRevision(promptId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  updateAuthorRevisionRequest(requestId: TtalkakId, payload: TtalkakPayload, token: TtalkakToken): Promise<unknown>;
  updateAdminRevisionRequestStatus(requestId: TtalkakId, status: string, token: TtalkakToken, memo?: string): Promise<unknown>;
  hideAdminComment(commentId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  unhideAdminComment(commentId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  deleteAdminComment(commentId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  hideAdminPrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  restoreAdminPrompt(promptId: TtalkakId, token: TtalkakToken): Promise<unknown>;
  [method: string]: unknown;
}

interface Window {
  __API_BASE_URL__?: string;
  TTALKAK_API_BASE_URL?: string;
  TTALKAK_API_TIMEOUT_MS?: number | string;
  TTALKAK_API_CORE: any;
  TTALKAK_API_NORMALIZERS: any;
  TTALKAK_AUTH_API: (context: any) => any;
  TTALKAK_PROMPT_API: (context: any) => any;
  TTALKAK_COMMENT_API: (context: any) => any;
  TTALKAK_MYPAGE_API: (context: any) => any;
  TTALKAK_MAKE_API: (context: any) => any;
  TTALKAK_ADMIN_API: (context: any) => any;
  TtalkakMakeMessageModel: any;
  TTALKAK_API: TtalkakApi;
  TtalkakApiContract: {
    assertApiContract(api: unknown): TtalkakApi;
    assertRecordResponse(value: unknown, operation?: string): Record<string, unknown>;
    assertCollectionResponse(value: unknown, operation?: string): unknown[];
    validateApiResponse(method: string, value: unknown): unknown;
    wrapApiResponses(api: TtalkakApi): TtalkakApi;
  };
  TTALKAK_GOOGLE_CREDENTIAL?: string;
  TtalkakHomeSearchModel: unknown;
  TtalkakHomeController: unknown;
  TtalkakHomeEvents: unknown;
  TtalkakPromptEngagementController: unknown;
  TtalkakPromptEngagementEvents: unknown;
  TtalkakCommentModel: unknown;
  TtalkakCommentView: unknown;
  TtalkakPromptWorkflows: unknown;
  TtalkakShareController: unknown;
  TtalkakShareEvents: unknown;
  TtalkakModalController: unknown;
  TtalkakModalEvents: unknown;
  TtalkakModalView: unknown;
  TtalkakAuthSession: unknown;
  TtalkakAuthValidation: unknown;
  TtalkakAuthController: unknown;
  TtalkakAuthEvents: unknown;
  TtalkakAuthView: unknown;
  TtalkakAdminEvents: unknown;
  TtalkakAdminSelectors: unknown;
  TtalkakAdminController: unknown;
  TtalkakAdminView: unknown;
  TtalkakAppBootstrap: unknown;
  TtalkakMakeController: unknown;
  TtalkakMakeEvents: unknown;
  TtalkakMakeFocus: unknown;
  TtalkakMakePersistence: unknown;
  TtalkakMakeState: unknown;
  TtalkakMakeWorkflows: unknown;
  TtalkakMakeSyncWorkflows: unknown;
  TtalkakMakeFolderWorkflows: unknown;
  TtalkakMakeExecutionWorkflows: unknown;
  TtalkakMakeRecentWorkflows: unknown;
}
