(function attachAdminEvents(global) { "use strict";
  function bindAdminEvents(root, ctx) {
    const { state, actions } = ctx;
    root.querySelectorAll("[data-admin-hide-prompt]").forEach((button) => button.addEventListener("click", () => actions.togglePromptHidden(button.dataset.adminHidePrompt)));
    root.querySelectorAll("[data-admin-prompt-search]").forEach((input) => { input.addEventListener("compositionstart", () => { state.isComposingAdminPromptSearch = true; actions.cancelPromptSearch(); }); input.addEventListener("compositionend", () => { state.isComposingAdminPromptSearch = false; actions.schedulePromptSearch(input.value); }); input.addEventListener("input", (event) => { if (!state.isComposingAdminPromptSearch && !event.isComposing) actions.schedulePromptSearch(input.value); }); });
    root.querySelectorAll("[data-admin-prompt-filter]").forEach((button) => button.addEventListener("click", () => { state.adminPromptFilter = button.dataset.adminPromptFilter || "all"; actions.render(); }));
    root.querySelectorAll("[data-admin-report-filter]").forEach((button) => button.addEventListener("click", () => { state.adminReportFilter = button.dataset.adminReportFilter || "all"; actions.render(); }));
    root.querySelectorAll("[data-admin-report-status]").forEach((button) => button.addEventListener("click", () => { const value = String(button.dataset.adminReportStatus || ""); const index = value.lastIndexOf(":"); actions.updateReportStatus(value.slice(0, index), value.slice(index + 1)); }));
    root.querySelectorAll("[data-admin-tag-search]").forEach((input) => { input.addEventListener("compositionstart", () => { state.isComposingAdminTagSearch = true; actions.cancelTagSearch(); }); input.addEventListener("compositionend", () => { state.isComposingAdminTagSearch = false; actions.scheduleTagSearch(input.value); }); input.addEventListener("input", (event) => { if (!state.isComposingAdminTagSearch && !event.isComposing) actions.scheduleTagSearch(input.value); }); });
    root.querySelectorAll("[data-admin-tag-filter]").forEach((button) => button.addEventListener("click", () => { state.adminTagFilter = button.dataset.adminTagFilter || "all"; actions.render(); }));
    root.querySelectorAll("[data-admin-tag-sort]").forEach((select) => select.addEventListener("change", () => { state.adminTagSort = select.value || "usage"; actions.render(); }));
    root.querySelectorAll("[data-admin-tag-action]").forEach((button) => button.addEventListener("click", () => { const [decision, tag] = String(button.dataset.adminTagAction || "").split(":"); if (!tag) return; if (decision === "disabled") actions.confirm({ type: "admin-tag-status", targetId: tag, value: decision, title: "태그 추천 제외", message: "이 태그를 추천 태그 목록에서 제외할까요? 필요하면 태그 관리에서 추천 복구할 수 있습니다.", confirmLabel: "추천 제외", danger: true }); else actions.updateTag(tag, decision); }));
    root.querySelectorAll("[data-admin-tag-prompts]").forEach((button) => button.addEventListener("click", () => { const tag = button.dataset.adminTagPrompts || ""; state.adminTagPromptKey = state.adminTagPromptKey === tag ? "" : tag; actions.render(); }));
    root.querySelectorAll("[data-admin-user-block]").forEach((button) => button.addEventListener("click", () => { state.adminBlockTarget = { memberId: button.dataset.adminUserBlock, nickname: button.dataset.adminUserName || state.adminUserActivityNickname || "사용자" }; actions.render(); }));
    root.querySelectorAll("[data-admin-user-unblock]").forEach((button) => button.addEventListener("click", () => actions.updateUserBlock(button.dataset.adminUserUnblock, false, button.dataset.adminUserName)));
    root.querySelectorAll("[data-admin-tab]").forEach((button) => button.addEventListener("click", () => { state.adminTab = button.dataset.adminTab || "reports"; actions.render(); }));
    root.querySelectorAll("[data-admin-request-revision]").forEach((button) => button.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); state.adminRequestTargetKey = button.dataset.adminRequestRevision; actions.render(); }));
  }
  const api = Object.freeze({ bindAdminEvents }); if (typeof module !== "undefined" && module.exports) module.exports = api; global.TtalkakAdminEvents = api;
})(typeof window !== "undefined" ? window : globalThis);
