import { unwrapItems } from "../core-api.mjs";
import { isWithdrawnUser, makePreviewText, normalizeAuthor, toNumber, toTimestamp, WITHDRAWN_USER_LABEL } from "./common.mjs";
import { normalizeComment } from "./comment.mjs";
import { normalizePopularTag, normalizePrompt } from "./prompt.mjs";

export function normalizeAdminTag(item, index = 0) { const label = normalizePopularTag(item) || `tag-${index}`; const raw = String(item?.status || "pending").toLowerCase(); return { id: String(item?.id || item?.tagId || label), key: label.toLowerCase(), label, status: ["approved", "rejected", "pending", "disabled"].includes(raw) ? raw : "pending", count: toNumber(item?.useCount, item?.count, item?.usageCount), recentAt: toTimestamp(item?.createdAt, item?.updatedAt), raw: item }; }
export function normalizeRevisionRequest(item, index = 0) { const prompt = item?.prompt && typeof item.prompt === "object" ? normalizePrompt(item.prompt) : null; const type = String(item?.targetType || item?.type || (item?.commentId ? "comment" : "prompt")).toLowerCase(); return { id: String(item?.id || item?.requestId || item?.revisionRequestId || `backend-revision-${index}`), key: `${type}:${item?.targetId || item?.promptId || item?.commentId || prompt?.id || item?.id || index}`, type, targetId: String(item?.targetId || item?.promptId || item?.commentId || prompt?.id || ""), promptId: String(item?.promptId || prompt?.id || ""), status: String(item?.status || "pending").toLowerCase(), reason: String(item?.reason || item?.memo || item?.adminMemo || item?.message || ""), requestedAt: toTimestamp(item?.requestedAt, item?.createdAt, item?.createdDate), reviewedAt: item?.reviewedAt ? toTimestamp(item.reviewedAt) : 0, prompt, raw: item }; }
export function normalizeAdminUser(item, index = 0) { const data = item?.data && typeof item.data === "object" ? item.data : item || {}; const active = !isWithdrawnUser(data); return { id: String(data.id || data.memberId || data.userId || `admin-user-${index}`), nickname: active ? normalizeAuthor(data, data.nickname || data.memberNickname || data.name || "사용자") : WITHDRAWN_USER_LABEL, active, blocked: Boolean(data.blocked ?? data.isBlocked ?? false), raw: data }; }
export function normalizeAdminUserActivitySummary(payload) { const data = payload?.data && typeof payload.data === "object" ? payload.data : payload || {}; const user = normalizeAdminUser(data.user || data.member || data); return { nickname: user.nickname, memberId: user.id, blocked: user.blocked, active: user.active, summary: data.counts || data.summary || {}, prompts: [], comments: [], replies: [], reportsMade: [], reportsReceived: [], raw: data }; }
export function normalizeAdminUserPromptActivity(item, index = 0) { const prompt = normalizePrompt(item, index); return { title: prompt.title, preview: String(item?.preview || makePreviewText(prompt.text)), promptId: prompt.id, commentId: "", occurredAt: prompt.createdAt, raw: item }; }
export function normalizeAdminUserCommentActivity(item, index = 0) { const comment = normalizeComment(item, index); return { title: String(item?.promptTitle || item?.prompt?.title || comment.promptTitle || "댓글"), preview: comment.deleted ? "삭제된 댓글입니다." : makePreviewText(comment.text), promptId: String(item?.promptId || item?.prompt?.id || comment.promptId || ""), commentId: comment.id, occurredAt: comment.createdAt, raw: item }; }
export function normalizeReport(item, index = 0) { const type = String(item?.targetType || item?.type || "prompt").toLowerCase(); const prompt = item?.prompt && typeof item.prompt === "object" ? normalizePrompt(item.prompt) : null; const targetAuthor = item?.targetAuthor || item?.targetAuthorNickname || item?.commentAuthorNickname || item?.promptAuthorNickname || item?.author || ""; const commentAuthor = type === "comment" ? item?.commentAuthor || item?.commentAuthorNickname || item?.author || item?.authorNickname || targetAuthor : item?.commentAuthor || item?.commentAuthorNickname || ""; return { id: String(item?.id || item?.reportId || `backend-report-${index}`), key: `${type}:${item?.targetId || item?.promptId || item?.commentId || item?.id || index}`, type, targetId: String(item?.targetId || item?.promptId || item?.commentId || ""), promptId: item?.promptId ? String(item.promptId) : prompt?.id || "", status: String(item?.status || "pending").toLowerCase(), reason: item?.reason || "", memo: item?.memo || "", reviewedAt: item?.reviewedAt ? toTimestamp(item.reviewedAt) : 0, createdAt: toTimestamp(item?.createdAt, item?.createdDate), title: item?.title || item?.targetTitle || item?.promptTitle || prompt?.title || "", contextTitle: item?.contextTitle || item?.promptTitle || prompt?.title || "", summary: item?.summary || item?.description || "", targetPreview: item?.targetPreview || item?.commentText || item?.targetText || item?.promptText || item?.text || prompt?.text || "", reporter: normalizeAuthor(item?.reporter || item?.reporterNickname || item?.reporterName || "", ""), targetAuthor: normalizeAuthor(targetAuthor, ""), promptAuthor: normalizeAuthor(item?.promptAuthor || item?.promptAuthorNickname || prompt?.author || "", ""), commentAuthor: normalizeAuthor(commentAuthor, ""), raw: item }; }
export function normalizeAdminUserReportActivity(item, index = 0) { const report = normalizeReport(item, index); return { title: report.type === "comment" ? `댓글 신고 · ${report.contextTitle || report.title || "게시물 확인 필요"}` : report.title || "프롬프트 신고", preview: String(report.reason || report.targetPreview || report.summary || "신고 내용 확인 필요"), promptId: report.promptId, commentId: report.type === "comment" ? report.targetId : "", occurredAt: report.createdAt, raw: item }; }
export const getPageItems = (payload) => unwrapItems(payload);
export function normalizeAdminAuditLog(item, index = 0) { const actor = item?.actor || item?.admin || item?.member || {}; return { id: String(item?.id || item?.auditLogId || `audit-${index}`), action: String(item?.action || item?.event || item?.type || ""), targetType: String(item?.targetType || item?.resourceType || item?.domain || ""), targetId: String(item?.targetId || item?.resourceId || item?.promptId || item?.commentId || item?.memberId || ""), actor: normalizeAuthor(actor, item?.actorNickname || item?.adminNickname || item?.memberNickname || "관리자"), memo: String(item?.detail || item?.memo || item?.reason || item?.message || item?.description || ""), createdAt: toTimestamp(item?.createdAt, item?.loggedAt, item?.timestamp), raw: item }; }
export function normalizeAdminUserActivity(payload) {
  const data = payload?.data && typeof payload.data === "object" ? payload.data : payload || {};
  const member = data.member || data.user || {};
  const status = { ...data, ...member };
  const active = !isWithdrawnUser(status);
  const groups = { prompts: [], comments: [], replies: [], reportsMade: [], reportsReceived: [] };
  unwrapItems(data.activities || data.items || data.content).forEach((activity) => {
    const type = String(activity?.type || "").toLowerCase();
    const item = { title: String(activity?.title || activity?.promptTitle || activity?.targetTitle || type || "활동"), preview: String(activity?.preview || activity?.text || activity?.content || activity?.reason || ""), promptId: activity?.promptId ? String(activity.promptId) : "", commentId: activity?.commentId || activity?.id ? String(activity.commentId || activity.id) : "", occurredAt: toTimestamp(activity?.occurredAt, activity?.createdAt, activity?.updatedAt), raw: activity };
    if (type === "prompt") groups.prompts.push(item); else if (type === "comment") groups.comments.push(item); else if (type === "reply") groups.replies.push(item); else if (type === "report" || type === "report_made") groups.reportsMade.push(item); else if (type === "reported" || type === "report_received") groups.reportsReceived.push(item);
  });
  return { nickname: active ? normalizeAuthor(member, data.nickname || data.memberNickname || "사용자") : WITHDRAWN_USER_LABEL, memberId: String(member.id || member.memberId || data.memberId || data.userId || data.id || ""), active, blocked: Boolean(member.blocked ?? member.isBlocked ?? data.blocked ?? data.isBlocked ?? false), blockReason: String(member.blockReason || data.blockReason || data.reason || ""), summary: data.summary || {}, ...groups, raw: data };
}
